export interface ISEORoute {
  slug: string;
  url: string;
  title: string;
  h1: string;
  description: string;
  keywords: string[];
  from: string;
  to?: string;
  category: "transfer" | "airport-transfer" | "day-trip";
  serviceType: "PRIVATE_TRANSFER" | "AIRPORT_TRANSFER" | "DAY_TRIP";
  isHub?: boolean;
}

export const SEO_ROUTES: Record<string, ISEORoute> = {
  // === TRANSFER HUBS ===
  "dublin": {
    slug: "dublin",
    url: "/transfers/dublin",
    title: "Dublin Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Dublin",
    description: "Book luxury private transfers and chauffeur services in Dublin with Tourenzo. Professional drivers, premium vehicles, and transparent fixed pricing.",
    keywords: ["Private transfers in Dublin", "Private transfers from Dublin", "Dublin private transfers", "Dublin chauffeur service"],
    from: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },
  "cork": {
    slug: "cork",
    url: "/transfers/cork",
    title: "Cork Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Cork",
    description: "Experience premium private transfers in Cork. Tourenzo provides comfortable, reliable chauffeur travel across Cork city and county.",
    keywords: ["Private transfers in Cork", "Cork private transfers", "Cork chauffeur service"],
    from: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },
  "galway": {
    slug: "galway",
    url: "/transfers/galway",
    title: "Galway Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Galway",
    description: "Book reliable private transfers in Galway. Luxury fleet, expert local chauffeurs, and door-to-door comfort for all destinations.",
    keywords: ["Private transfers in Galway", "Galway private transfers", "Galway chauffeur service"],
    from: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },
  "limerick": {
    slug: "limerick",
    url: "/transfers/limerick",
    title: "Limerick Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Limerick",
    description: "Premium private chauffeur and transfer service in Limerick. Safe, stylish, and punctual travel across Ireland.",
    keywords: ["Private transfers in Limerick", "Limerick private transfers", "Limerick chauffeur service"],
    from: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },
  "belfast": {
    slug: "belfast",
    url: "/transfers/belfast",
    title: "Belfast Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Belfast",
    description: "Private transfers in Belfast and cross-border chauffeur service to Dublin and Northern Ireland with Tourenzo.",
    keywords: ["Private transfers in Belfast", "Belfast private transfers", "Belfast chauffeur service"],
    from: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },
  "killarney": {
    slug: "killarney",
    url: "/transfers/killarney",
    title: "Killarney Private Transfers & Chauffeur Service | Tourenzo",
    h1: "Private Transfers in Killarney",
    description: "Discover County Kerry with Tourenzo's luxury private transfers in Killarney. Door-to-door chauffeur service for tourists and executives.",
    keywords: ["Private transfers in Killarney", "Killarney private transfers", "Killarney chauffeur service"],
    from: "Killarney",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  },

  // === DUBLIN TRANSFERS ===
  "dublin-to-galway": {
    slug: "dublin-to-galway",
    url: "/transfers/dublin-to-galway/",
    title: "Private Transfer from Dublin to Galway | Tourenzo",
    h1: "Private Transfer from Dublin to Galway",
    description: "Book a direct private transfer from Dublin to Galway. Relax in luxury Mercedes vehicles with professional chauffeurs and door-to-door comfort.",
    keywords: ["Private transfer Dublin to Galway", "Dublin to Galway transfer", "Dublin to Galway chauffeur"],
    from: "Dublin",
    to: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "dublin-to-cork": {
    slug: "dublin-to-cork",
    url: "/transfers/dublin-to-cork/",
    title: "Private Transfer from Dublin to Cork | Tourenzo",
    h1: "Private Transfer from Dublin to Cork",
    description: "Travel comfortably from Dublin to Cork with Tourenzo's private transfer. Fixed transparent rates, wifi onboard, and luxury fleet.",
    keywords: ["Private transfer Dublin to Cork", "Dublin to Cork transfer", "Dublin to Cork chauffeur"],
    from: "Dublin",
    to: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "dublin-to-limerick": {
    slug: "dublin-to-limerick",
    url: "/transfers/dublin-to-limerick/",
    title: "Private Transfer from Dublin to Limerick | Tourenzo",
    h1: "Private Transfer from Dublin to Limerick",
    description: "Executive private transfer between Dublin and Limerick. Direct door-to-door service with licensed professional chauffeurs.",
    keywords: ["Private transfer Dublin to Limerick", "Dublin to Limerick transfer", "Dublin to Limerick chauffeur"],
    from: "Dublin",
    to: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "dublin-to-belfast": {
    slug: "dublin-to-belfast",
    url: "/transfers/dublin-to-belfast/",
    title: "Private Transfer from Dublin to Belfast | Tourenzo",
    h1: "Private Transfer from Dublin to Belfast",
    description: "Seamless cross-border private transfer from Dublin to Belfast. Travel in premium comfort with zero hassle.",
    keywords: ["Private transfer Dublin to Belfast", "Dublin to Belfast transfer", "Dublin to Belfast chauffeur"],
    from: "Dublin",
    to: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "dublin-to-killarney": {
    slug: "dublin-to-killarney",
    url: "/transfers/dublin-to-killarney/",
    title: "Private Transfer from Dublin to Killarney | Tourenzo",
    h1: "Private Transfer from Dublin to Killarney",
    description: "Luxury private chauffeur transfer from Dublin directly to Killarney and the Ring of Kerry. Spacious vehicles for family and luggage.",
    keywords: ["Private transfer Dublin to Killarney", "Dublin to Killarney transfer", "Dublin to Killarney chauffeur"],
    from: "Dublin",
    to: "Killarney",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "dublin-to-shannon-airport": {
    slug: "dublin-to-shannon-airport",
    url: "/transfers/dublin-to-shannon-airport/",
    title: "Private Transfer from Dublin to Shannon Airport | Tourenzo",
    h1: "Private Transfer from Dublin to Shannon Airport",
    description: "Reliable airport transfer from Dublin city or Dublin Airport to Shannon Airport (SNN) with guaranteed on-time pickup.",
    keywords: ["Private transfer Dublin to Shannon Airport", "Dublin to Shannon Airport transfer"],
    from: "Dublin",
    to: "Shannon Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === CORK TRANSFERS ===
  "cork-to-galway": {
    slug: "cork-to-galway",
    url: "/transfers/cork-to-galway/",
    title: "Private Transfer from Cork to Galway | Tourenzo",
    h1: "Private Transfer from Cork to Galway",
    description: "Direct private transfer from Cork to Galway along the Wild Atlantic Way corridor. Premium comfort and scenic routes.",
    keywords: ["Private transfer Cork to Galway", "Cork to Galway transfer"],
    from: "Cork",
    to: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-dublin": {
    slug: "cork-to-dublin",
    url: "/transfers/cork-to-dublin/",
    title: "Private Transfer from Cork to Dublin | Tourenzo",
    h1: "Private Transfer from Cork to Dublin",
    description: "Private chauffeur transfer from Cork city or County Cork to Dublin city center or Dublin Airport.",
    keywords: ["Private transfer Cork to Dublin", "Cork to Dublin transfer"],
    from: "Cork",
    to: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-dublin-airport": {
    slug: "cork-to-dublin-airport",
    url: "/transfers/cork-to-dublin-airport/",
    title: "Private Transfer from Cork to Dublin Airport | Tourenzo",
    h1: "Private Transfer from Cork to Dublin Airport",
    description: "Direct executive airport transfer from Cork straight to Dublin Airport departures terminal (T1 & T2).",
    keywords: ["Private transfer Cork to Dublin Airport", "Cork to Dublin Airport transfer"],
    from: "Cork",
    to: "Dublin Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-limerick": {
    slug: "cork-to-limerick",
    url: "/transfers/cork-to-limerick/",
    title: "Private Transfer from Cork to Limerick | Tourenzo",
    h1: "Private Transfer from Cork to Limerick",
    description: "Fast and comfortable private transfer between Cork and Limerick with dedicated professional chauffeurs.",
    keywords: ["Private transfer Cork to Limerick", "Cork to Limerick transfer"],
    from: "Cork",
    to: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-belfast": {
    slug: "cork-to-belfast",
    url: "/transfers/cork-to-belfast/",
    title: "Private Transfer from Cork to Belfast | Tourenzo",
    h1: "Private Transfer from Cork to Belfast",
    description: "Direct intercity private transfer connecting Cork to Belfast with luxury Mercedes sedans and executive vans.",
    keywords: ["Private transfer Cork to Belfast", "Cork to Belfast transfer"],
    from: "Cork",
    to: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-killarney": {
    slug: "cork-to-killarney",
    url: "/transfers/cork-to-killarney/",
    title: "Private Transfer from Cork to Killarney | Tourenzo",
    h1: "Private Transfer from Cork to Killarney",
    description: "Travel in style from Cork to Killarney. The perfect private transfer for exploring County Kerry and West Cork.",
    keywords: ["Private transfer Cork to Killarney", "Cork to Killarney transfer"],
    from: "Cork",
    to: "Killarney",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-shannon-airport": {
    slug: "cork-to-shannon-airport",
    url: "/transfers/cork-to-shannon-airport/",
    title: "Private Transfer from Cork to Shannon Airport | Tourenzo",
    h1: "Private Transfer from Cork to Shannon Airport",
    description: "Direct private airport transfer from Cork to Shannon Airport departures with flight tracking and punctual pickup.",
    keywords: ["Private transfer Cork to Shannon Airport", "Cork to Shannon Airport transfer"],
    from: "Cork",
    to: "Shannon Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "cork-to-dingle": {
    slug: "cork-to-dingle",
    url: "/transfers/cork-to-dingle/",
    title: "Private Transfer from Cork to Dingle | Tourenzo",
    h1: "Private Transfer from Cork to Dingle",
    description: "Scenic private transfer from Cork city or Cork Airport to the Dingle Peninsula with Tourenzo.",
    keywords: ["Private transfer Cork to Dingle", "Cork to Dingle transfer"],
    from: "Cork",
    to: "Dingle",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === GALWAY TRANSFERS ===
  "galway-to-dublin": {
    slug: "galway-to-dublin",
    url: "/transfers/galway-to-dublin/",
    title: "Private Transfer from Galway to Dublin | Tourenzo",
    h1: "Private Transfer from Galway to Dublin",
    description: "Executive private transfer from Galway city directly to Dublin. Clean luxury cars, professional drivers, and door-to-door comfort.",
    keywords: ["Private transfer Galway to Dublin", "Galway to Dublin transfer", "Galway to Dublin chauffeur"],
    from: "Galway",
    to: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-dublin-airport": {
    slug: "galway-to-dublin-airport",
    url: "/transfers/galway-to-dublin-airport/",
    title: "Private Transfer from Galway to Dublin Airport | Tourenzo",
    h1: "Private Transfer from Galway to Dublin Airport",
    description: "Guaranteed on-time private transfer from Galway straight to Dublin Airport (DUB) departures terminal.",
    keywords: ["Private transfer Galway to Dublin Airport", "Galway to Dublin Airport transfer"],
    from: "Galway",
    to: "Dublin Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-cork": {
    slug: "galway-to-cork",
    url: "/transfers/galway-to-cork/",
    title: "Private Transfer from Galway to Cork | Tourenzo",
    h1: "Private Transfer from Galway to Cork",
    description: "Private chauffeur transfer connecting Galway to Cork with comfort and style. Optional scenic stops available.",
    keywords: ["Private transfer Galway to Cork", "Galway to Cork transfer"],
    from: "Galway",
    to: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-limerick": {
    slug: "galway-to-limerick",
    url: "/transfers/galway-to-limerick/",
    title: "Private Transfer from Galway to Limerick | Tourenzo",
    h1: "Private Transfer from Galway to Limerick",
    description: "Quick and dependable private transfer service between Galway and Limerick.",
    keywords: ["Private transfer Galway to Limerick", "Galway to Limerick transfer"],
    from: "Galway",
    to: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-belfast": {
    slug: "galway-to-belfast",
    url: "/transfers/galway-to-belfast/",
    title: "Private Transfer from Galway to Belfast | Tourenzo",
    h1: "Private Transfer from Galway to Belfast",
    description: "Private transfer connecting Galway to Belfast. Stress-free executive long-distance travel.",
    keywords: ["Private transfer Galway to Belfast", "Galway to Belfast transfer"],
    from: "Galway",
    to: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-killarney": {
    slug: "galway-to-killarney",
    url: "/transfers/galway-to-killarney/",
    title: "Private Transfer from Galway to Killarney | Tourenzo",
    h1: "Private Transfer from Galway to Killarney",
    description: "Seamless private transfer from Galway to Killarney across the west coast of Ireland.",
    keywords: ["Private transfer Galway to Killarney", "Galway to Killarney transfer"],
    from: "Galway",
    to: "Killarney",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "galway-to-shannon-airport": {
    slug: "galway-to-shannon-airport",
    url: "/transfers/galway-to-shannon-airport/",
    title: "Private Transfer from Galway to Shannon Airport | Tourenzo",
    h1: "Private Transfer from Galway to Shannon Airport",
    description: "Door-to-door private airport transfer from Galway to Shannon Airport (SNN). Perfect timing guaranteed.",
    keywords: ["Private transfer Galway to Shannon Airport", "Galway to Shannon Airport transfer"],
    from: "Galway",
    to: "Shannon Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === LIMERICK TRANSFERS ===
  "limerick-to-dublin": {
    slug: "limerick-to-dublin",
    url: "/transfers/limerick-to-dublin/",
    title: "Private Transfer from Limerick to Dublin | Tourenzo",
    h1: "Private Transfer from Limerick to Dublin",
    description: "Private transfer from Limerick to Dublin city center or Dublin Airport with professional chauffeurs.",
    keywords: ["Private transfer Limerick to Dublin", "Limerick to Dublin transfer"],
    from: "Limerick",
    to: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-dublin-airport": {
    slug: "limerick-to-dublin-airport",
    url: "/transfers/limerick-to-dublin-airport/",
    title: "Private Transfer from Limerick to Dublin Airport | Tourenzo",
    h1: "Private Transfer from Limerick to Dublin Airport",
    description: "Fast and reliable private airport transfer from Limerick to Dublin Airport departures.",
    keywords: ["Private transfer Limerick to Dublin Airport", "Limerick to Dublin Airport transfer"],
    from: "Limerick",
    to: "Dublin Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-cork": {
    slug: "limerick-to-cork",
    url: "/transfers/limerick-to-cork/",
    title: "Private Transfer from Limerick to Cork | Tourenzo",
    h1: "Private Transfer from Limerick to Cork",
    description: "Private chauffeur service from Limerick to Cork. Safe, comfortable, and executive vehicles.",
    keywords: ["Private transfer Limerick to Cork", "Limerick to Cork transfer"],
    from: "Limerick",
    to: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-galway": {
    slug: "limerick-to-galway",
    url: "/transfers/limerick-to-galway/",
    title: "Private Transfer from Limerick to Galway | Tourenzo",
    h1: "Private Transfer from Limerick to Galway",
    description: "Private direct transfer from Limerick to Galway city. Book online with instant confirmation.",
    keywords: ["Private transfer Limerick to Galway", "Limerick to Galway transfer"],
    from: "Limerick",
    to: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-belfast": {
    slug: "limerick-to-belfast",
    url: "/transfers/limerick-to-belfast/",
    title: "Private Transfer from Limerick to Belfast | Tourenzo",
    h1: "Private Transfer from Limerick to Belfast",
    description: "Long-distance executive transfer from Limerick to Belfast with Tourenzo.",
    keywords: ["Private transfer Limerick to Belfast", "Limerick to Belfast transfer"],
    from: "Limerick",
    to: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-killarney": {
    slug: "limerick-to-killarney",
    url: "/transfers/limerick-to-killarney/",
    title: "Private Transfer from Limerick to Killarney | Tourenzo",
    h1: "Private Transfer from Limerick to Killarney",
    description: "Private transfer connecting Limerick to Killarney and County Kerry. Safe and smooth chauffeur service.",
    keywords: ["Private transfer Limerick to Killarney", "Limerick to Killarney transfer"],
    from: "Limerick",
    to: "Killarney",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "limerick-to-shannon-airport": {
    slug: "limerick-to-shannon-airport",
    url: "/transfers/limerick-to-shannon-airport/",
    title: "Private Transfer from Limerick to Shannon Airport | Tourenzo",
    h1: "Private Transfer from Limerick to Shannon Airport",
    description: "Fast 25-minute private transfer from Limerick to Shannon Airport (SNN) with luggage assistance.",
    keywords: ["Private transfer Limerick to Shannon Airport", "Limerick to Shannon Airport transfer"],
    from: "Limerick",
    to: "Shannon Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === BELFAST TRANSFERS ===
  "belfast-to-dublin": {
    slug: "belfast-to-dublin",
    url: "/transfers/belfast-to-dublin/",
    title: "Private Transfer from Belfast to Dublin | Tourenzo",
    h1: "Private Transfer from Belfast to Dublin",
    description: "Cross-border private transfer from Belfast to Dublin city or Dublin Airport with luxury chauffeur service.",
    keywords: ["Private transfer Belfast to Dublin", "Belfast to Dublin transfer"],
    from: "Belfast",
    to: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "belfast-to-dublin-airport": {
    slug: "belfast-to-dublin-airport",
    url: "/transfers/belfast-to-dublin-airport/",
    title: "Private Transfer from Belfast to Dublin Airport | Tourenzo",
    h1: "Private Transfer from Belfast to Dublin Airport",
    description: "Direct executive airport transfer from Belfast to Dublin Airport (DUB) departures.",
    keywords: ["Private transfer Belfast to Dublin Airport", "Belfast to Dublin Airport transfer"],
    from: "Belfast",
    to: "Dublin Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "belfast-to-cork": {
    slug: "belfast-to-cork",
    url: "/transfers/belfast-to-cork/",
    title: "Private Transfer from Belfast to Cork | Tourenzo",
    h1: "Private Transfer from Belfast to Cork",
    description: "Long-distance executive transfer from Belfast to Cork with premium Mercedes vehicles.",
    keywords: ["Private transfer Belfast to Cork", "Belfast to Cork transfer"],
    from: "Belfast",
    to: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "belfast-to-galway": {
    slug: "belfast-to-galway",
    url: "/transfers/belfast-to-galway/",
    title: "Private Transfer from Belfast to Galway | Tourenzo",
    h1: "Private Transfer from Belfast to Galway",
    description: "Direct private transfer connecting Belfast to Galway with executive door-to-door service.",
    keywords: ["Private transfer Belfast to Galway", "Belfast to Galway transfer"],
    from: "Belfast",
    to: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "belfast-to-limerick": {
    slug: "belfast-to-limerick",
    url: "/transfers/belfast-to-limerick/",
    title: "Private Transfer from Belfast to Limerick | Tourenzo",
    h1: "Private Transfer from Belfast to Limerick",
    description: "Comfortable private transfer from Belfast to Limerick with Tourenzo.",
    keywords: ["Private transfer Belfast to Limerick", "Belfast to Limerick transfer"],
    from: "Belfast",
    to: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === KILLARNEY TRANSFERS ===
  "killarney-to-dublin": {
    slug: "killarney-to-dublin",
    url: "/transfers/killarney-to-dublin/",
    title: "Private Transfer from Killarney to Dublin | Tourenzo",
    h1: "Private Transfer from Killarney to Dublin",
    description: "Private chauffeur transfer from Killarney to Dublin city or Dublin Airport.",
    keywords: ["Private transfer Killarney to Dublin", "Killarney to Dublin transfer"],
    from: "Killarney",
    to: "Dublin",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-dublin-airport": {
    slug: "killarney-to-dublin-airport",
    url: "/transfers/killarney-to-dublin-airport/",
    title: "Private Transfer from Killarney to Dublin Airport | Tourenzo",
    h1: "Private Transfer from Killarney to Dublin Airport",
    description: "Direct airport transfer from Killarney to Dublin Airport departures.",
    keywords: ["Private transfer Killarney to Dublin Airport", "Killarney to Dublin Airport transfer"],
    from: "Killarney",
    to: "Dublin Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-cork": {
    slug: "killarney-to-cork",
    url: "/transfers/killarney-to-cork/",
    title: "Private Transfer from Killarney to Cork | Tourenzo",
    h1: "Private Transfer from Killarney to Cork",
    description: "Private transfer connecting Killarney to Cork city center or Cork Airport.",
    keywords: ["Private transfer Killarney to Cork", "Killarney to Cork transfer"],
    from: "Killarney",
    to: "Cork",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-cork-airport": {
    slug: "killarney-to-cork-airport",
    url: "/transfers/killarney-to-cork-airport/",
    title: "Private Transfer from Killarney to Cork Airport | Tourenzo",
    h1: "Private Transfer from Killarney to Cork Airport",
    description: "Direct transfer from Killarney to Cork Airport (ORK) with professional chauffeur.",
    keywords: ["Private transfer Killarney to Cork Airport", "Killarney to Cork Airport transfer"],
    from: "Killarney",
    to: "Cork Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-galway": {
    slug: "killarney-to-galway",
    url: "/transfers/killarney-to-galway/",
    title: "Private Transfer from Killarney to Galway | Tourenzo",
    h1: "Private Transfer from Killarney to Galway",
    description: "Private chauffeur transfer from Killarney to Galway city along the Wild Atlantic Way.",
    keywords: ["Private transfer Killarney to Galway", "Killarney to Galway transfer"],
    from: "Killarney",
    to: "Galway",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-belfast": {
    slug: "killarney-to-belfast",
    url: "/transfers/killarney-to-belfast/",
    title: "Private Transfer from Killarney to Belfast | Tourenzo",
    h1: "Private Transfer from Killarney to Belfast",
    description: "Long-distance executive transfer connecting Killarney to Belfast.",
    keywords: ["Private transfer Killarney to Belfast", "Killarney to Belfast transfer"],
    from: "Killarney",
    to: "Belfast",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-limerick": {
    slug: "killarney-to-limerick",
    url: "/transfers/killarney-to-limerick/",
    title: "Private Transfer from Killarney to Limerick | Tourenzo",
    h1: "Private Transfer from Killarney to Limerick",
    description: "Door-to-door private transfer from Killarney to Limerick.",
    keywords: ["Private transfer Killarney to Limerick", "Killarney to Limerick transfer"],
    from: "Killarney",
    to: "Limerick",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-shannon-airport": {
    slug: "killarney-to-shannon-airport",
    url: "/transfers/killarney-to-shannon-airport/",
    title: "Private Transfer from Killarney to Shannon Airport | Tourenzo",
    h1: "Private Transfer from Killarney to Shannon Airport",
    description: "Guaranteed on-time private transfer from Killarney to Shannon Airport (SNN).",
    keywords: ["Private transfer Killarney to Shannon Airport", "Killarney to Shannon Airport transfer"],
    from: "Killarney",
    to: "Shannon Airport",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },
  "killarney-to-dingle": {
    slug: "killarney-to-dingle",
    url: "/transfers/killarney-to-dingle/",
    title: "Private Transfer from Killarney to Dingle | Tourenzo",
    h1: "Private Transfer from Killarney to Dingle",
    description: "Scenic private transfer from Killarney to the Dingle Peninsula with luxury vehicles.",
    keywords: ["Private transfer Killarney to Dingle", "Killarney to Dingle transfer"],
    from: "Killarney",
    to: "Dingle",
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
  },

  // === AIRPORT HUBS ===
  "shannon-airport": {
    slug: "shannon-airport",
    url: "/airport-transfers/shannon-airport",
    title: "Shannon Airport Transfers | Private Airport Transfers | Tourenzo",
    h1: "Shannon Airport Transfers",
    description: "Book private airport transfers to and from Shannon Airport (SNN) with Tourenzo. Flight monitoring, Meet & Greet, and luxury Mercedes vehicles.",
    keywords: ["Shannon Airport Transfers", "Shannon airport taxi", "Shannon airport chauffeur"],
    from: "Shannon Airport",
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  },
  "dublin-airport": {
    slug: "dublin-airport",
    url: "/airport-transfers/dublin-airport",
    title: "Dublin Airport Transfers | Private Airport Transfers | Tourenzo",
    h1: "Dublin Airport Transfers",
    description: "Private chauffeur transfers from Dublin Airport (DUB) to Dublin City, Galway, Cork, Belfast and all across Ireland.",
    keywords: ["Dublin Airport Transfers", "Dublin airport transfer", "Dublin airport taxi", "Dublin airport chauffeur"],
    from: "Dublin Airport",
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  },
  "cork-airport": {
    slug: "cork-airport",
    url: "/airport-transfers/cork-airport",
    title: "Cork Airport Transfers | Private Airport Transfers | Tourenzo",
    h1: "Cork Airport Transfers",
    description: "Professional private airport transfer service to and from Cork Airport (ORK) with executive vehicles.",
    keywords: ["Cork Airport Transfers", "Cork airport transfer", "Cork airport taxi"],
    from: "Cork Airport",
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  },
  "knock-airport": {
    slug: "knock-airport",
    url: "/airport-transfers/knock-airport",
    title: "Knock Airport Transfers | Private Airport Transfers | Tourenzo",
    h1: "Knock Airport Transfers",
    description: "Private transfers to and from Ireland West Airport Knock (NOC) across Connacht and County Mayo.",
    keywords: ["Knock Airport Transfers", "Knock airport transfer"],
    from: "Knock Airport",
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  },
  "kerry-airport": {
    slug: "kerry-airport",
    url: "/airport-transfers/kerry-airport",
    title: "Kerry Airport Transfers | Private Airport Transfers | Tourenzo",
    h1: "Kerry Airport Transfers",
    description: "Private transfers from Kerry Airport (KIR) to Killarney, Tralee, and Dingle with Tourenzo.",
    keywords: ["Kerry Airport Transfers", "Kerry airport transfer"],
    from: "Kerry Airport",
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  },

  // === AIRPORT ROUTES ===
  "shannon-airport-to-dublin": {
    slug: "shannon-airport-to-dublin",
    url: "/transfers/shannon-airport-to-dublin/",
    title: "Private Transfer From Shannon Airport To Dublin | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Dublin",
    description: "Direct private transfer from Shannon Airport arrivals to Dublin city or Dublin Airport.",
    keywords: ["Private Transfer from Shannon Airport to Dublin", "Shannon to Dublin transfer"],
    from: "Shannon Airport",
    to: "Dublin",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-cork": {
    slug: "shannon-airport-to-cork",
    url: "/transfers/shannon-airport-to-cork/",
    title: "Private Transfer From Shannon Airport To Cork | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Cork",
    description: "Private chauffeur transfer from Shannon Airport to Cork city center or hotels.",
    keywords: ["Private Transfer from Shannon Airport to Cork", "Shannon to Cork transfer"],
    from: "Shannon Airport",
    to: "Cork",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-galway": {
    slug: "shannon-airport-to-galway",
    url: "/transfers/shannon-airport-to-galway/",
    title: "Private Transfer From Shannon Airport To Galway | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Galway",
    description: "Executive private transfer from Shannon Airport to Galway. Fast 1 hour 15 min journey.",
    keywords: ["Private Transfer from Shannon Airport to Galway", "Shannon to Galway transfer"],
    from: "Shannon Airport",
    to: "Galway",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-belfast": {
    slug: "shannon-airport-to-belfast",
    url: "/transfers/shannon-airport-to-belfast/",
    title: "Private Transfer From Shannon Airport To Belfast | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Belfast",
    description: "Private transfer connecting Shannon Airport to Belfast with luxury fleet.",
    keywords: ["Private Transfer from Shannon Airport to Belfast"],
    from: "Shannon Airport",
    to: "Belfast",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-limerick": {
    slug: "shannon-airport-to-limerick",
    url: "/transfers/shannon-airport-to-limerick/",
    title: "Private Transfer From Shannon Airport To Limerick | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Limerick",
    description: "Fast 25-minute executive airport transfer from Shannon Airport to Limerick city.",
    keywords: ["Private Transfer from Shannon Airport to Limerick"],
    from: "Shannon Airport",
    to: "Limerick",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-killarney": {
    slug: "shannon-airport-to-killarney",
    url: "/transfers/shannon-airport-to-killarney/",
    title: "Private Transfer From Shannon Airport To Killarney | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Killarney",
    description: "Direct private transfer from Shannon Airport to Killarney and County Kerry.",
    keywords: ["Private Transfer from Shannon Airport to Killarney"],
    from: "Shannon Airport",
    to: "Killarney",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-dingle": {
    slug: "shannon-airport-to-dingle",
    url: "/transfers/shannon-airport-to-dingle/",
    title: "Private Transfer From Shannon Airport To Dingle | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Dingle",
    description: "Chauffeur transfer from Shannon Airport to the Dingle Peninsula with Tourenzo.",
    keywords: ["Private Transfer from Shannon Airport to Dingle"],
    from: "Shannon Airport",
    to: "Dingle",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-lahinch": {
    slug: "shannon-airport-to-lahinch",
    url: "/transfers/shannon-airport-to-lahinch/",
    title: "Private Transfer From Shannon Airport To Lahinch | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Lahinch",
    description: "Direct transfer from Shannon Airport to Lahinch Golf Club and coastal resorts.",
    keywords: ["Private Transfer from Shannon Airport to Lahinch"],
    from: "Shannon Airport",
    to: "Lahinch",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-ennis": {
    slug: "shannon-airport-to-ennis",
    url: "/transfers/shannon-airport-to-ennis/",
    title: "Private Transfer From Shannon Airport To Ennis | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Ennis",
    description: "Quick private transfer from Shannon Airport to Ennis town center and hotels.",
    keywords: ["Private Transfer from Shannon Airport to Ennis"],
    from: "Shannon Airport",
    to: "Ennis",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-adare": {
    slug: "shannon-airport-to-adare",
    url: "/transfers/shannon-airport-to-adare/",
    title: "Private Transfer From Shannon Airport To Adare | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Adare",
    description: "Private luxury transfer from Shannon Airport to Adare Manor and village.",
    keywords: ["Private Transfer from Shannon Airport to Adare"],
    from: "Shannon Airport",
    to: "Adare",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "shannon-airport-to-doolin": {
    slug: "shannon-airport-to-doolin",
    url: "/transfers/shannon-airport-to-doolin/",
    title: "Private Transfer From Shannon Airport To Doolin | Tourenzo",
    h1: "Private Transfer from Shannon Airport to Doolin",
    description: "Private chauffeur transfer from Shannon Airport to Doolin and the Cliffs of Moher.",
    keywords: ["Private Transfer from Shannon Airport to Doolin"],
    from: "Shannon Airport",
    to: "Doolin",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },

  // === DUBLIN AIRPORT ROUTES ===
  "dublin-airport-to-dublin-city": {
    slug: "dublin-airport-to-dublin-city",
    url: "/transfers/dublin-airport-to-dublin-city/",
    title: "Dublin Airport to Dublin City Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Dublin City",
    description: "Seamless Meet & Greet private chauffeur transfer from Dublin Airport (DUB) to any address or hotel in Dublin City.",
    keywords: ["Private Transfer from Dublin Airport to Dublin City", "Dublin airport to city taxi"],
    from: "Dublin Airport",
    to: "Dublin City",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-cork": {
    slug: "dublin-airport-to-cork",
    url: "/transfers/dublin-airport-to-cork/",
    title: "Dublin Airport to Cork Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Cork",
    description: "Direct long-distance private transfer from Dublin Airport arrivals straight to Cork.",
    keywords: ["Private Transfer from Dublin Airport to Cork", "Dublin Airport to Cork transfer"],
    from: "Dublin Airport",
    to: "Cork",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-galway": {
    slug: "dublin-airport-to-galway",
    url: "/transfers/dublin-airport-to-galway/",
    title: "Dublin Airport to Galway Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Galway",
    description: "Direct door-to-door private transfer from Dublin Airport (DUB) to Galway city and surrounding areas.",
    keywords: ["Private Transfer from Dublin Airport to Galway", "Dublin Airport to Galway transfer"],
    from: "Dublin Airport",
    to: "Galway",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-belfast": {
    slug: "dublin-airport-to-belfast",
    url: "/transfers/dublin-airport-to-belfast/",
    title: "Dublin Airport to Belfast Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Belfast",
    description: "Cross-border executive chauffeur transfer from Dublin Airport to Belfast in under 2 hours.",
    keywords: ["Private Transfer from Dublin Airport to Belfast"],
    from: "Dublin Airport",
    to: "Belfast",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-limerick": {
    slug: "dublin-airport-to-limerick",
    url: "/transfers/dublin-airport-to-limerick/",
    title: "Dublin Airport to Limerick Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Limerick",
    description: "Executive private transfer from Dublin Airport to Limerick with flight monitoring and luggage assistance.",
    keywords: ["Private Transfer from Dublin Airport to Limerick"],
    from: "Dublin Airport",
    to: "Limerick",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-killarney": {
    slug: "dublin-airport-to-killarney",
    url: "/transfers/dublin-airport-to-killarney/",
    title: "Dublin Airport to Killarney Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Killarney",
    description: "Direct private transfer from Dublin Airport to Killarney hotels and resorts.",
    keywords: ["Private Transfer from Dublin Airport to Killarney"],
    from: "Dublin Airport",
    to: "Killarney",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-kilkenny": {
    slug: "dublin-airport-to-kilkenny",
    url: "/transfers/dublin-airport-to-kilkenny/",
    title: "Dublin Airport to Kilkenny Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Kilkenny",
    description: "Direct private chauffeur transfer from Dublin Airport to medieval Kilkenny city.",
    keywords: ["Private Transfer from Dublin Airport to Kilkenny"],
    from: "Dublin Airport",
    to: "Kilkenny",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-waterford": {
    slug: "dublin-airport-to-waterford",
    url: "/transfers/dublin-airport-to-waterford/",
    title: "Dublin Airport to Waterford Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Waterford",
    description: "Private airport transfer from Dublin Airport to Waterford city and County Waterford.",
    keywords: ["Private Transfer from Dublin Airport to Waterford"],
    from: "Dublin Airport",
    to: "Waterford",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "dublin-airport-to-wexford": {
    slug: "dublin-airport-to-wexford",
    url: "/transfers/dublin-airport-to-wexford/",
    title: "Dublin Airport to Wexford Private Transfer | Tourenzo",
    h1: "Private Transfer from Dublin Airport to Wexford",
    description: "Direct executive transfer from Dublin Airport to Wexford town and coast.",
    keywords: ["Private Transfer from Dublin Airport to Wexford"],
    from: "Dublin Airport",
    to: "Wexford",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },

  // === CORK AIRPORT ROUTES ===
  "cork-airport-to-dublin": {
    slug: "cork-airport-to-dublin",
    url: "/transfers/cork-airport-to-dublin/",
    title: "Cork Airport to Dublin Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Dublin",
    description: "Direct private transfer connecting Cork Airport to Dublin city or Dublin Airport.",
    keywords: ["Cork Airport to Dublin Private Transfer"],
    from: "Cork Airport",
    to: "Dublin",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "cork-airport-to-galway": {
    slug: "cork-airport-to-galway",
    url: "/transfers/cork-airport-to-galway/",
    title: "Cork Airport to Galway Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Galway",
    description: "Private transfer from Cork Airport straight to Galway city.",
    keywords: ["Cork Airport to Galway Private Transfer"],
    from: "Cork Airport",
    to: "Galway",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "cork-airport-to-killarney": {
    slug: "cork-airport-to-killarney",
    url: "/transfers/cork-airport-to-killarney/",
    title: "Cork Airport to Killarney Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Killarney",
    description: "Executive chauffeur transfer from Cork Airport to Killarney and County Kerry.",
    keywords: ["Cork Airport to Killarney Private Transfer"],
    from: "Cork Airport",
    to: "Killarney",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "cork-airport-to-cork-city": {
    slug: "cork-airport-to-cork-city",
    url: "/transfers/cork-airport-to-cork-city/",
    title: "Cork Airport to Cork City Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Cork City",
    description: "Quick, reliable private transfer from Cork Airport to any Cork city destination.",
    keywords: ["Cork Airport to Cork City Private Transfer"],
    from: "Cork Airport",
    to: "Cork City",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "cork-airport-to-kinsale": {
    slug: "cork-airport-to-kinsale",
    url: "/transfers/cork-airport-to-kinsale/",
    title: "Cork Airport to Kinsale Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Kinsale",
    description: "Fast 20-minute private transfer from Cork Airport to the gourmet capital of Kinsale.",
    keywords: ["Cork Airport to Kinsale Private Transfer"],
    from: "Cork Airport",
    to: "Kinsale",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "cork-airport-to-limerick": {
    slug: "cork-airport-to-limerick",
    url: "/transfers/cork-airport-to-limerick/",
    title: "Cork Airport to Limerick Private Transfer | Tourenzo",
    h1: "Private Transfer from Cork Airport to Limerick",
    description: "Comfortable private transfer from Cork Airport to Limerick.",
    keywords: ["Cork Airport to Limerick Private Transfer"],
    from: "Cork Airport",
    to: "Limerick",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },

  // === KNOCK AIRPORT ROUTES ===
  "knock-airport-to-galway": {
    slug: "knock-airport-to-galway",
    url: "/transfers/knock-airport-to-galway/",
    title: "Knock Airport to Galway Private Transfer | Tourenzo",
    h1: "Private Transfer from Knock Airport to Galway",
    description: "Reliable airport transfer from Ireland West Airport Knock (NOC) to Galway city.",
    keywords: ["Knock Airport to Galway Private Transfer"],
    from: "Knock Airport",
    to: "Galway",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "knock-airport-to-castlebar": {
    slug: "knock-airport-to-castlebar",
    url: "/transfers/knock-airport-to-castlebar/",
    title: "Knock Airport to Castlebar Private Transfer | Tourenzo",
    h1: "Private Transfer from Knock Airport to Castlebar",
    description: "Quick private transfer from Knock Airport to Castlebar town.",
    keywords: ["Knock Airport to Castlebar Private Transfer"],
    from: "Knock Airport",
    to: "Castlebar",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },

  // === KERRY AIRPORT ROUTES ===
  "kerry-airport-to-killarney": {
    slug: "kerry-airport-to-killarney",
    url: "/transfers/kerry-airport-to-killarney/",
    title: "Kerry Airport to Killarney Private Transfer | Tourenzo",
    h1: "Private Transfer from Kerry Airport to Killarney",
    description: "Fast 15-minute private transfer from Kerry Airport (KIR) to Killarney hotels.",
    keywords: ["Kerry Airport to Killarney Private Transfer"],
    from: "Kerry Airport",
    to: "Killarney",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "kerry-airport-to-tralee": {
    slug: "kerry-airport-to-tralee",
    url: "/transfers/kerry-airport-to-tralee/",
    title: "Kerry Airport to Tralee Private Transfer | Tourenzo",
    h1: "Private Transfer from Kerry Airport to Tralee",
    description: "Direct transfer from Kerry Airport to Tralee town center.",
    keywords: ["Kerry Airport to Tralee Private Transfer"],
    from: "Kerry Airport",
    to: "Tralee",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },
  "kerry-airport-to-dingle": {
    slug: "kerry-airport-to-dingle",
    url: "/transfers/kerry-airport-to-dingle/",
    title: "Kerry Airport to Dingle Private Transfer | Tourenzo",
    h1: "Private Transfer from Kerry Airport to Dingle",
    description: "Scenic private transfer from Kerry Airport to the Dingle Peninsula.",
    keywords: ["Kerry Airport to Dingle Private Transfer"],
    from: "Kerry Airport",
    to: "Dingle",
    category: "transfer",
    serviceType: "AIRPORT_TRANSFER",
  },

  // === DAY TRIPS ===
  "dublin-day-trips": {
    slug: "dublin",
    url: "/day-trips/dublin/",
    title: "Private Day Trips from Dublin | Dublin Day Tours | Tourenzo",
    h1: "Private Day Trips from Dublin",
    description: "Explore the best day trips from Dublin with a private driver. Cliffs of Moher, Wicklow, Giants Causeway, and Blarney Castle.",
    keywords: ["Private Day Trips from Dublin", "Dublin Day Tours", "Dublin day trips"],
    from: "Dublin",
    category: "day-trip",
    serviceType: "DAY_TRIP",
    isHub: true,
  },
  "dublin-to-cliffs-of-moher": {
    slug: "dublin-to-cliffs-of-moher",
    url: "/day-trips/dublin-to-cliffs-of-moher/",
    title: "Private Day Trip from Dublin to Cliffs of Moher | Tourenzo",
    h1: "Dublin to Cliffs of Moher Day Trip",
    description: "Experience the iconic Cliffs of Moher on an exclusive private day tour from Dublin. Customized stops at Burren and Doolin included.",
    keywords: ["Private Day Trip from Dublin to Cliffs of Moher", "Dublin to Cliffs of Moher Day Trip"],
    from: "Dublin",
    to: "Cliffs of Moher",
    category: "day-trip",
    serviceType: "DAY_TRIP",
  },
  "dublin-to-belfast-dunluce-castle-giants-causeway": {
    slug: "dublin-to-belfast-dunluce-castle-giants-causeway",
    url: "/day-trips/dublin-to-belfast-dunluce-castle-giants-causeway/",
    title: "Private Day Trip from Dublin to Belfast & Giant's Causeway | Tourenzo",
    h1: "Dublin to Belfast, Dunluce Castle & Giant's Causeway Day Trip",
    description: "Full-day private guided tour from Dublin to Belfast, Dunluce Castle, and the Giant's Causeway in luxury vehicles.",
    keywords: ["Private Day Trip from Dublin to Belfast & Giant's Causeway", "Belfast and Giants Causeway tour"],
    from: "Dublin",
    to: "Belfast & Giant's Causeway",
    category: "day-trip",
    serviceType: "DAY_TRIP",
  },
  "dublin-to-kilkenny-wicklow-glendalough-sheepdog-trial": {
    slug: "dublin-to-kilkenny-wicklow-glendalough-sheepdog-trial",
    url: "/day-trips/dublin-to-kilkenny-wicklow-glendalough-sheepdog-trial/",
    title: "Dublin to Kilkenny, Wicklow & Glendalough Day Trip | Tourenzo",
    h1: "Dublin to Kilkenny, Wicklow, Glendalough & Sheepdog Trial Day Trip",
    description: "Discover ancient Glendalough, Wicklow Mountains, and Kilkenny Castle on a private day trip from Dublin with live sheepdog trial.",
    keywords: ["Dublin to Kilkenny, Wicklow & Glendalough Day Trip", "Wicklow day tour"],
    from: "Dublin",
    to: "Kilkenny & Wicklow",
    category: "day-trip",
    serviceType: "DAY_TRIP",
  },
  "dublin-to-cork-blarney-stone": {
    slug: "dublin-to-cork-blarney-stone",
    url: "/day-trips/dublin-to-cork-blarney-stone/",
    title: "Dublin to Cork & Blarney Stone | Private Guided Tour | Tourenzo",
    h1: "Dublin to Cork & Blarney Stone Private Guided Day Trip",
    description: "Private day trip from Dublin to Cork city, Rock of Cashel, and Blarney Castle to kiss the legendary Blarney Stone.",
    keywords: ["Dublin to Cork & Blarney Stone", "Private Guided Day Trip"],
    from: "Dublin",
    to: "Cork & Blarney Stone",
    category: "day-trip",
    serviceType: "DAY_TRIP",
  },
  "dublin-to-howth-malahide": {
    slug: "dublin-to-howth-malahide",
    url: "/day-trips/dublin-to-howth-malahide/",
    title: "Dublin to Howth & Malahide | Private Guided Day Trip | Tourenzo",
    h1: "Dublin to Howth & Malahide Private Guided Day Trip",
    description: "Half-day or full-day private coastal tour from Dublin to scenic Howth Cliff walk and historic Malahide Castle.",
    keywords: ["Dublin to Howth & Malahide", "Private Guided Day Trip"],
    from: "Dublin",
    to: "Howth & Malahide",
    category: "day-trip",
    serviceType: "DAY_TRIP",
  },
};

export function getTransferRouteBySlug(rawSlug: string): ISEORoute {
  // Strict sanitization: Strip any non-alphanumeric and non-hyphen characters
  const clean = (rawSlug || "").toLowerCase().replace(/[^a-z0-9-]/g, "");

  if (SEO_ROUTES[clean]) {
    return SEO_ROUTES[clean];
  }

  // Dynamic fallback for any slug with "-to-"
  if (clean.includes("-to-")) {
    const parts = clean.split("-to-");
    const formatName = (str: string) =>
      str
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");

    const from = formatName(parts[0]);
    const to = formatName(parts[1]);

    return {
      slug: clean,
      url: `/transfers/${clean}/`,
      title: `Private Transfer from ${from} to ${to} | Tourenzo`,
      h1: `Private Transfer from ${from} to ${to}`,
      description: `Book a comfortable, reliable private chauffeur transfer from ${from} to ${to} with Tourenzo. Luxury vehicles, fixed pricing, and professional service.`,
      keywords: [`Private transfer ${from} to ${to}`, `${from} to ${to} transfer`],
      from,
      to,
      category: "transfer",
      serviceType: "PRIVATE_TRANSFER",
    };
  }

  // Single city fallback
  const cityName = clean
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return {
    slug: clean,
    url: `/transfers/${clean}/`,
    title: `${cityName} Private Transfers & Chauffeur Service | Tourenzo`,
    h1: `Private Transfers in ${cityName}`,
    description: `Book private chauffeur transfers and executive car service in ${cityName} with Tourenzo.`,
    keywords: [`Private transfers in ${cityName}`, `${cityName} private transfers`],
    from: cityName,
    category: "transfer",
    serviceType: "PRIVATE_TRANSFER",
    isHub: true,
  };
}

export function getAirportTransferBySlug(rawSlug: string): ISEORoute {
  // Strict sanitization
  const clean = (rawSlug || "").toLowerCase().replace(/[^a-z0-9-]/g, "");
  if (SEO_ROUTES[clean]) return SEO_ROUTES[clean];

  const airportName = clean
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return {
    slug: clean,
    url: `/airport-transfers/${clean}`,
    title: `${airportName} Transfers | Private Airport Transfers | Tourenzo`,
    h1: `${airportName} Transfers`,
    description: `Book private airport transfers to and from ${airportName} with Tourenzo. Meet & Greet, fixed pricing, and luxury vehicles.`,
    keywords: [`${airportName} Transfers`, `${airportName} transfer`],
    from: airportName,
    category: "airport-transfer",
    serviceType: "AIRPORT_TRANSFER",
    isHub: true,
  };
}

export function getDayTripBySlug(rawSlug: string): ISEORoute {
  // Strict sanitization
  const clean = (rawSlug || "").toLowerCase().replace(/[^a-z0-9-]/g, "");
  if (SEO_ROUTES[clean]) return SEO_ROUTES[clean];

  const titleName = clean
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return {
    slug: clean,
    url: `/day-trips/${clean}/`,
    title: `${titleName} Day Trip | Tourenzo`,
    h1: `${titleName} Private Guided Day Trip`,
    description: `Experience ${titleName} on an exclusive private day tour with Tourenzo.`,
    keywords: [`${titleName} day trip`, `${titleName} tour`],
    from: "Dublin",
    to: titleName,
    category: "day-trip",
    serviceType: "DAY_TRIP",
  };
}
